package com.devarena.challenge.model;

public enum ChallengeCategory {
    ARRAYS,
    STRINGS,
    LINKED_LIST,
    STACK_QUEUE,
    TREES,
    GRAPHS,
    DYNAMIC_PROGRAMMING,
    BINARY_SEARCH,
    BACKTRACKING,
    HEAPS_PRIORITY_QUEUES,
    BIT_MANIPULATION,
    GREEDY,
    DATABASE,
    SQL,
    DBMS,
    OPERATING_SYSTEMS,
    NETWORKING,
    MATH_APTITUDE,
    PUZZLES,
    SYSTEM_DESIGN,
    ALGORITHMS,
    DEBUGGING,
    INTERVIEW_PREP,
    GENERAL_CS
}
