package com.devarena.admin.model;

public enum AdminAuditAction {
    PLAYER_SUSPENDED,
    PLAYER_RESTORED,
    CHALLENGE_CREATED,
    CHALLENGE_UPDATED,
    CHALLENGE_PUBLISHED,
    CHALLENGE_ARCHIVED,
    REPORT_RESOLVED,
    REPORT_DISMISSED,
    INTEGRITY_EVENT_REVIEWED
}
